DROP TABLE IF EXISTS sports_bets CASCADE;
DROP TABLE IF EXISTS sports_selections CASCADE;
DROP TABLE IF EXISTS sports_markets CASCADE;
DROP TABLE IF EXISTS sports_events CASCADE;
DROP TABLE IF EXISTS sports CASCADE;
